### ISSUE TITLE
How to generate the instruction doc?

### ISSUE THREAD

**Issue by blackholemedia** [mgao6767/legao#1]
Where is the implementation of generation instruction file? I can get an instruction excel file on the website, but I did not find the implementation from the source code. Thanks in advance.

**Comment by mgao6767** [comment]
Hi, this repo for now contains only the initial code. Functions implemented later haven't been added. I'll be making a new version of the site with more features and publish to GitHub.

**Comment by blackholemedia** [comment]
Cool, thanks for your impressive work!
